# Generated by Django 2.2.4 on 2019-08-06 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('slogan', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=350)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='accounts.User')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proveedor', to='accounts.User')),
            ],
        ),
    ]
