# Generated by Django 2.2.4 on 2019-08-06 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190806_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='address',
        ),
        migrations.AddField(
            model_name='phone',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Address'),
            preserve_default=False,
        ),
    ]
