# Generated by Django 2.2.4 on 2019-08-06 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190806_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='date_creatd',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='connection',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proveedor', to='accounts.User'),
        ),
    ]
